import { useState } from 'react';
import { useNavigate } from 'react-router-dom';

function Signup() {
  const [role, setRole] = useState('student');
  const [signupMode, setSignupMode] = useState('manual'); // 'manual' or 'idcard'
  const [username, setUsername] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [idCard, setIdCard] = useState(null);
  const navigate = useNavigate();

  const handleSignup = (e) => {
    e.preventDefault();

    if (role === 'student') {
      if (signupMode === 'idcard' && !idCard) {
        alert('Please upload ID card image.');
        return;
      }
      if (signupMode === 'manual' && (!username || !email || !password)) {
        alert('Fill all fields for manual signup.');
        return;
      }
    } else if (!username || !email || !password) {
      alert('All fields required.');
      return;
    }

    // Simulated logic
    console.log({
      role,
      signupMode,
      username: signupMode === 'idcard' ? 'ExtractedStudentName' : username,
      email,
      password,
      idCard: idCard?.name || null,
    });

    alert('Signup successful!');
    navigate('/');
  };

  const handleFileChange = (e) => {
    setIdCard(e.target.files[0]);
    // Simulate auto-filling from ID card image
    setUsername('StudentNameFromID');
    setEmail('student@example.com');
    setPassword('autogenerated');
  };

  return (
    <div style={styles.container}>
      <h2>Signup</h2>

      <form onSubmit={handleSignup} style={styles.form}>
        <select
          value={role}
          onChange={(e) => {
            setRole(e.target.value);
            setSignupMode('manual'); // reset on role change
          }}
          style={styles.input}
        >
          <option value="student">Student</option>
          <option value="hod">HOD</option>
          <option value="dean">Dean</option>
          <option value="director">Director</option>
          <option value="doctor">Doctor</option>
          <option value="faculty">Faculty</option>
          <option value="admin">Admin</option>
        </select>

        {role === 'student' && (
          <div style={{ marginBottom: '10px' }}>
            <label>
              <input
                type="radio"
                value="idcard"
                checked={signupMode === 'idcard'}
                onChange={() => setSignupMode('idcard')}
              />
              Signup with ID Card
            </label>
            &nbsp;&nbsp;
            <label>
              <input
                type="radio"
                value="manual"
                checked={signupMode === 'manual'}
                onChange={() => setSignupMode('manual')}
              />
              Manual Signup
            </label>
          </div>
        )}

        {/* ID card based form */}
        {role === 'student' && signupMode === 'idcard' && (
          <>
            <label>Upload ID Card (Image):</label>
            <input type="file" accept="image/*" onChange={handleFileChange} />
            <p style={{ fontSize: '12px', color: 'gray' }}>
              (Simulates auto-fill: Name = "StudentNameFromID", Email = "student@example.com")
            </p>
          </>
        )}

        {/* Manual entry form */}
        {(role !== 'student' || signupMode === 'manual') && (
          <>
            <input
              type="text"
              placeholder="Username"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              style={styles.input}
            />
            <input
              type="email"
              placeholder="Email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              style={styles.input}
            />
            <input
              type="password"
              placeholder="Password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              style={styles.input}
            />
          </>
        )}

        <button type="submit" style={styles.button}>Signup</button>
      </form>
    </div>
  );
}

const styles = {
  container: {
    maxWidth: '500px',
    margin: '80px auto',
    padding: '20px',
    border: '1px solid #ccc',
    borderRadius: '8px',
    textAlign: 'center',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  input: {
    padding: '10px',
    fontSize: '16px',
  },
  button: {
    padding: '10px',
    fontSize: '16px',
    background: '#28a745',
    color: '#fff',
    border: 'none',
    borderRadius: '4px',
    marginTop: '10px',
  },
};

export default Signup;
